FROM 172.31.4.157:5000/gizwits2015/gizwits-python:latest

MAINTAINER Jam Huang <jamhuang@gizwits.com>

RUN virtualenv /env-gw_reapi
RUN mkdir -p /gw_reapi
WORKDIR /gw_reapi
ADD deploy/requirement.txt.docker requirements.txt
#RUN /env-gw_reapi/bin/pip install -i http://172.32.1.187:3141/root/gizwits -r requirements.txt
RUN /env-gw_reapi/bin/pip install -r requirements.txt

ADD . /gw_reapi
ADD nginx.conf /etc/nginx/nginx.conf
ADD gw_reapi.conf /etc/nginx/sites-available/gw_reapi
RUN ln -s /etc/nginx/sites-available/gw_reapi /etc/nginx/sites-enabled/
RUN rm -f /etc/nginx/sites-enabled/default
ADD supervisord.conf.qa_pro supervisord.conf
RUN mkdir -p /data/nginx
RUN mkdir -p /data/supervisor

VOLUME /data/nginx
VOLUME /data/supervisor

RUN mkdir -p /swagger-ui
WORKDIR /swagger-ui
ADD swagger-ui/   /swagger-ui
WORKDIR /gw_reapi

EXPOSE 80

ENTRYPOINT ["/usr/bin/supervisord"]
CMD ["-n"]
